apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-${project.version}
  labels:
    app: ${project.artifactId}
    version: ${project.version}
spec:
  selector:
    app: ${project.artifactId}
