apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}-${project.version}
  version: ${project.version}
data:
  TICKETING_TICKETS_SERVICE_SALE_VITAMINE_ON: FALSE
  TICKETING_TICKETS_SERVICE_MESH_ON: FALSE
  TICKETING_TICKETS_STORE_KAFKA_ENABLED: TRUE
  TICKETING_STOCK_PROCESSOR_SERVICE_URI: "http://istio-ingressgateway/api/ticket"
  TICKETING_EVENT_VERSION: "1.0"
  TICKETING_SERVICE_VERSION: "${project.version}"
  TICKETING_TICKETS_DESTINATION_NAME: "sales.ticketing.tickets.destination"
  TICKETING_TICKETS_BROKER_URI: "tcp://sales-event-store-amq-tcp:61616?jms.redeliveryPolicy.maximumRedeliveries=10"
  TICKETING_TICKETS_BROKER_USERNAME: "sales-event-store"
  TICKETING_TICKETS_STORE_AMQ_ENABLED: FALSE
  TICKETING_METRICS_ENABLED: TRUE
  TICKETING_METRICS_WEB_EXPOSURE_INCLUDE: "*"
  TICKETING_METRICS_PROMETHEUS_ENABLED: TRUE
  TICKETING_METRICS_PROMETHEUS_EXPORT_ENABLED: TRUE
  TICKETING_METRICS_ARTIFACTID_NAME: "${project.artifactId}"
