apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}-${project.version}
  labels:
    app: ${project.artifactId}
    version: ${project.version}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${project.artifactId}
      version: ${project.version}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ${project.artifactId}
        version: ${project.version}
    spec:
      containers:
        - 
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: "TICKETING_TICKETS_SERVICE_SALE_VITAMINE_ON"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_SERVICE_SALE_VITAMINE_ON
            - name: "TICKETING_TICKETS_SERVICE_MESH_ON"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_SERVICE_MESH_ON
            - name: "TICKETING_STOCK_PROCESSOR_SERVICE_URI"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_STOCK_PROCESSOR_SERVICE_URI
            - name: "TICKETING_EVENT_VERSION"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_EVENT_VERSION
            - name: "TICKETING_SERVICE_VERSION"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_SERVICE_VERSION
            - name: "TICKETING_TICKETS_DESTINATION_NAME"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_DESTINATION_NAME
            - name: "TICKETING_TICKETS_BROKER_URI"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_BROKER_URI
            - name: "TICKETING_TICKETS_BROKER_USERNAME"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_BROKER_USERNAME
            - name: "TICKETING_TICKETS_STORE_AMQ_ENABLED"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_STORE_AMQ_ENABLED
            - name: "TICKETING_TICKETS_BROKER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: ticket-processor-service-secret
                  key: TICKETING_TICKETS_BROKER_PASSWORD
            - name: "TICKETING_METRICS_ENABLED"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_METRICS_ENABLED
            - name: "TICKETING_METRICS_WEB_EXPOSURE_INCLUDE"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_METRICS_WEB_EXPOSURE_INCLUDE
            - name: "TICKETING_METRICS_PROMETHEUS_ENABLED"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_METRICS_PROMETHEUS_ENABLED
            - name: "TICKETING_METRICS_PROMETHEUS_EXPORT_ENABLED"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_METRICS_PROMETHEUS_EXPORT_ENABLED
            - name: "TICKETING_METRICS_ARTIFACTID_NAME"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_METRICS_ARTIFACTID_NAME
            - name: "TICKETING_TICKETS_STORE_KAFKA_ENABLED"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_STORE_KAFKA_ENABLED
            - name: "TICKETING_TICKETS_KAFKA_BOOTSTRAP_SERVERS"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_KAFKA_BOOTSTRAP_SERVERS
            - name: "TICKETING_TICKETS_KAFKA_USERNAME"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_KAFKA_USERNAME
            - name: "TICKETING_TICKETS_KAFKA_DESTINATION_NAME"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: TICKETING_TICKETS_KAFKA_DESTINATION_NAME
            - name: "TICKETING_ORDERS_COMMANDS_KAFKA_DESTINATION_NAME"
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${project.version}
                  key: "TICKETING_ORDERS_COMMANDS_KAFKA_DESTINATION_NAME"
