apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    custom-service: ${project.artifactId}
spec:
  ports:
    - name: http-web
      port: 8080
      targetPort: 8080
  selector:
    custom-service: ${project.artifactId}
