apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-${project.version}
  labels:
    app: ${project.artifactId}
    service: ${project.artifactId}
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${project.artifactId}
    version: ${project.version}