---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ticket-processor-endpoint
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: ticket-processor-endpoint@sha256:73502462461dd8796daa50dfb8b7b48bc4630467a89f84451c44b9bb24eb1d49
        namespace: sales-demo-app-dev
      name: latest
