apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "devops-tools-custom-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "1" 
        memory: "1Gi" 
      min:
        cpu: "1" 
        memory: "500Mi" 
