- name: Perform an OpenShift login
  hosts: localhost
  gather_facts: false
  tasks:
    - name: openShift login
      command: curl -X GET -H "Authorization\":\" Bearer {{ctti_ocp_token}}" {{ctti_ocp_url}}/oapi/v1 --insecure
    - name: sleep for 3 seconds and continue with play
      wait_for: timeout=3
      delegate_to: localhost
