apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: stock-query-service
spec:
  hosts:
  - 172.30.111.88
  http:
  - route:
    - destination:
        host: 172.30.111.88
        subset: stock-query-service-v1
      weight: 100
      