metadata:
  name: ${project.artifactId}-${project.version}
  labels:
    group: ${project.groupId}
    project: ${project.artifactId}-${project.version}
    version: ${project.version}
    provider: fabric8
spec:
  template:
    replicas: 2
    spec:
      containers:
      -
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
          - name: "STOCK_DATAGRID_BROKER_URI"
            value: "sales-data-store-hotrod"
          - name: "STOCK_DATAGRID_BROKER_URI_PORT"
            value: "11333"
          - name: "STOCK_DATAGRID_BROKER_USERNAME"
            value: "sales-data-store"
          - name: "STOCK_DATAGRID_BROKER_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: stock-query-service-secret
                key: STOCK_DATAGRID_BROKER_PASSWORD
          - name: "STOCK_SERVICE_VERSION"
            value: "${project.version}"
          - name: "STOCK_METRICS_ENABLED"
            value: TRUE
          - name: "STOCK_METRICS_WEB_EXPOSURE_INCLUDE"
            value: "*"
          - name: "STOCK_METRICS_PROMETHEUS_ENABLED"
            value: TRUE
          - name: "STOCK_METRICS_PROMETHEUS_EXPORT_ENABLED"
            value: TRUE
          - name: "STOCK_METRICS_ARTIFACTID_NAME"
            value: "${project.artifactId}"
