---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: stock-query-endpoint
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: stock-query-endpoint@sha256:c23905b2214b248def24c88893b54a22b7aebd86cac013da9da2ad8fc68f3259
        namespace: sales-demo-app-dev
      name: latest
