apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    service: ${project.artifactId}
    app: ${project.artifactId}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${project.artifactId}
