apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    version: v0
    app: ${project.artifactId}
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${project.artifactId}
