metadata:
  name: ${project.artifactId}
  labels:
    group: ${project.groupId}
    project: ${project.artifactId}
    version: ${project.version}
    provider: fabric8
    monitorGroup: ctti
spec:
  template:
    spec:
      containers:
        -
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 125
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: "TICKETING_EVENT_VERSION"
              value: "1.0"
            - name: "TICKETING_TICKETS_DESTINATION_NAME"
              value: "sales.ticketing.tickets.destination"
            - name: "TICKETING_TICKETS_BROKER_URI"
              value: "tcp://sales-event-store-amq-tcp:61616?jms.redeliveryPolicy.maximumRedeliveries=10"
            - name: "TICKETING_TICKETS_BROKER_USERNAME"
              value: "sales-event-store"
            - name: "TICKETING_TICKETS_STORE_AMQ_ENABLED"
              value: TRUE
            - name: "TICKETING_TICKETS_BROKER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: ticket-processor-service-secret
                  key: TICKETING_TICKETS_BROKER_PASSWORD
            - name: "TICKETING_METRICS_ENABLED"
              value: TRUE
            - name: "TICKETING_METRICS_WEB_EXPOSURE_INCLUDE"
              value: "*"
            - name: "TICKETING_METRICS_PROMETHEUS_ENABLED"
              value: TRUE
            - name: "TICKETING_METRICS_PROMETHEUS_EXPORT_ENABLED"
              value: TRUE
            - name: "TICKETING_METRICS_ARTIFACTID_NAME"
              value: "ticket-processor-service"
